#%RAML 1.0
title: Authorization API
version: v1
mediaType: application/json
baseUri: hb://auth

types:
  Validation:
    properties:
      authorization:
        type: string
        description: Authorization header value

  ValidationResult:
    properties:
      identity_keys:
        type: object
      extra:
        type: object

/validations:
  post:
    body:
      type: Validation
      example: {"authorization": "Basic QWxhZGRpbjpPcGVuU2VzYW1l"}
    responses:
      201:
        body:
          type: ValidationResult
          example: { "identity_keys": {"username": "Aladdin"}, "extra": {} }
