#%RAML 1.0

# Copyright (c) 2017 Magomed Abdurakhmanov, Hypertino
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

title: Authorization API
version: v1
mediaType: application/json
baseUri: hb://auth

types:
  AuthHeader:
    enum:
      - Authorization
      - Authorization-Result
      - Privilege-Authorization
      - Privilege-Authorization-Result
  Validation:
    properties:
      authorization:
        type: string
        description: Authorization header value

  ValidationResult:
    properties:
      identity_keys:
        type: object
      extra:
        type: object

/validations:
  post:
    body:
      type: Validation
      example: {"authorization": "Basic QWxhZGRpbjpPcGVuU2VzYW1l"}
    responses:
      201:
        body:
          type: ValidationResult
          example: { "identity_keys": {"username": "Aladdin"}, "extra": {} }
